Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -38,4 +38,19 @@ jobs:
       run: npm run build --if-present
     - name : change repo
       run : cd /home/newus-admin-kiosk/htdocs/admin-kiosk.newus.id/actions-runner/_work/mpp-admin-kiosk/mpp-admin-kiosk/kiosk-admin
-    # - run : pm2 restart mppdigital.newus.id
+    - name : Restart App
+      run :  |
+          APP_NAME="admin-kiosk.newus.id"
+          APP_ID="14"
+
+          if pm2 restart $APP_NAME; then
+            echo "Successfully restarted app with name $APP_NAME"
+          else
+            echo "Failed to restart app with name $APP_NAME, trying with ID $APP_ID"
+            if pm2 restart $APP_ID; then
+              echo "Successfully restarted app with ID $APP_ID"
+            else
+              echo "Failed to restart app with both name and ID"
+              exit 1
+            fi
+          fi
